//! Creates a framed screenshot by superimposing one or more simulator screenshots
//! into a device background image.
//!
//! The device backgrounds are those used by the simulator. Screenshots are assumed to be the correct
//! size when generated by the device simulator.
//!
//! Multiple screenshots are overlaid in order before the device frame is applied on top.
//! This is useful for compositing transparent-field-extracted PNGs together into a single view.
//!
//! If the `--crop-to-screenshot` flag is provided, the final image will be cropped to the dimensions
//! of the first screenshot, centered on the screenshot's position.
//!
//! Usage:
//!   frame_screenshot <device_background_path> <offset_x> <offset_y> <output_path> --screenshot <path> [--screenshot <path> ...] [--crop-to-screenshot]

use clap::Parser;
use image::{GenericImageView, ImageBuffer, RgbaImage};
use std::path::PathBuf;

#[derive(Parser)]
struct Args {
    device_background_path: PathBuf,
    offset_x: i64,
    offset_y: i64,
    output_path: PathBuf,

    /// Screenshot(s) to overlay onto the device frame (in order, bottom to top).
    /// Repeat this flag for multiple screenshots.
    #[clap(long = "screenshot", required = true)]
    screenshot_paths: Vec<PathBuf>,

    /// Optional background fill colour as #RRGGBB or #RRGGBBAA hex.
    /// If omitted, unfilled pixels remain fully transparent.
    #[clap(long)]
    background_color: Option<String>,

    #[clap(long)]
    crop_to_screenshot: bool,
}

fn parse_color(s: &str) -> Result<image::Rgba<u8>, Box<dyn std::error::Error>> {
    let s = s.trim_start_matches('#');
    let (r, g, b, a) = match s.len() {
        6 => {
            let r = u8::from_str_radix(&s[0..2], 16)?;
            let g = u8::from_str_radix(&s[2..4], 16)?;
            let b = u8::from_str_radix(&s[4..6], 16)?;
            (r, g, b, 255)
        }
        8 => {
            let r = u8::from_str_radix(&s[0..2], 16)?;
            let g = u8::from_str_radix(&s[2..4], 16)?;
            let b = u8::from_str_radix(&s[4..6], 16)?;
            let a = u8::from_str_radix(&s[6..8], 16)?;
            (r, g, b, a)
        }
        _ => return Err(format!("Invalid color '{}': expected #RRGGBB or #RRGGBBAA", s).into()),
    };
    Ok(image::Rgba([r, g, b, a]))
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();

    let background_img = image::open(&args.device_background_path)?.to_rgba8();
    let (bg_width, bg_height) = background_img.dimensions();
    let fill_pixel = match &args.background_color {
        Some(c) => parse_color(c)?,
        None    => image::Rgba([0, 0, 0, 0]),
    };
    let mut canvas: RgbaImage = ImageBuffer::from_pixel(bg_width, bg_height, fill_pixel);

    // Overlay each screenshot in order (first = bottom-most layer).
    for path in &args.screenshot_paths {
        let screenshot = image::open(path)?;
        image::imageops::overlay(&mut canvas, &screenshot, args.offset_x, args.offset_y);
    }

    // Overlay the device frame on top.
    image::imageops::overlay(&mut canvas, &background_img, 0, 0);

    if args.crop_to_screenshot {
        let first = image::open(&args.screenshot_paths[0])?;
        let (x, y) = (args.offset_x as u32, args.offset_y as u32);
        let (width, height) = first.dimensions();
        let cropped = image::imageops::crop(&mut canvas, x, y, width, height).to_image();
        cropped.save(&args.output_path)?;
    } else {
        canvas.save(&args.output_path)?;
    }

    Ok(())
}

